### ISSUE TITLE
Data scrapping for metanalysis 

### ISSUE THREAD

**Issue by krushnach80** [dsquintana/metameta#2]
Hi I was looking at your library I would love to use it for my analysis but the issue which im facing is very fundamental, since i have no idea how to start I can scrape pubmed or europmc using library i do get papers for the study which Im looking for. But for meta  analysis I do see the data is made in certain way such as this [https://europepmc.org/article/PMC/4419975](url) table 2.So my naive question is how do the tables are made is it manually or there is a programmatic way of doing it. 

I would be glad if you can suggest me a way that would be really helpful

**Comment by dsquintana** [comment]
There would probably be a way to scrape this data but I wouldn't know how do this. For now, data would need to be entered manually.

**Comment by krushnach80** [comment]
thanks for the reply i did manage to figure-out how to do that ..although final one need to be inspected manually.
